PARAMETERS = {'height': 120.0, 'wall_thickness': 0.2, 'body_diameter': 66.0, 'base_recess_depth': 2.8, 'base_mid_radius': 12.0, 'base_dish_radius': 23.5, 'base_dish_height': 1.4, 'base_foot_inner_radius': 28.5, 'base_foot_outer_radius': 31.0, 'base_lower_side_radius': 32.2, 'base_side_height': 2.0, 'lower_taper_height': 7.0, 'shoulder_start_height': 103.5, 'shoulder_end_height': 114.0, 'neck_radius': 30.8, 'lid_recess_depth': 1.4, 'rim_center_radius': 31.8, 'rim_tube_radius': 1.2}
import cadquery as cq
height = PARAMETERS['height']
wall_thickness = PARAMETERS['wall_thickness']
body_diameter = PARAMETERS['body_diameter']
base_recess_depth = PARAMETERS['base_recess_depth']
base_mid_radius = PARAMETERS['base_mid_radius']
base_dish_radius = PARAMETERS['base_dish_radius']
base_dish_height = PARAMETERS['base_dish_height']
base_foot_inner_radius = PARAMETERS['base_foot_inner_radius']
base_foot_outer_radius = PARAMETERS['base_foot_outer_radius']
base_lower_side_radius = PARAMETERS['base_lower_side_radius']
base_side_height = PARAMETERS['base_side_height']
lower_taper_height = PARAMETERS['lower_taper_height']
shoulder_start_height = PARAMETERS['shoulder_start_height']
shoulder_end_height = PARAMETERS['shoulder_end_height']
neck_radius = PARAMETERS['neck_radius']
lid_recess_depth = PARAMETERS['lid_recess_depth']
rim_center_radius = PARAMETERS['rim_center_radius']
rim_tube_radius = PARAMETERS['rim_tube_radius']
body_radius = body_diameter / 2.0
inner_body_radius = body_radius - wall_thickness
inner_neck_radius = neck_radius - wall_thickness
rim_center_height = height - rim_tube_radius
lid_top_height = height - lid_recess_depth
lid_bottom_height = lid_top_height - wall_thickness
profile = [(0.0, base_recess_depth), (base_mid_radius, base_recess_depth - wall_thickness), (base_dish_radius, base_dish_height), (base_foot_inner_radius, 0.0), (base_foot_outer_radius, 0.0), (base_lower_side_radius, base_side_height), (body_radius, lower_taper_height), (body_radius, shoulder_start_height), (neck_radius, shoulder_end_height), (neck_radius, lid_top_height), (0.0, lid_top_height), (0.0, lid_bottom_height), (inner_neck_radius, lid_bottom_height), (inner_neck_radius, shoulder_end_height), (inner_body_radius, shoulder_start_height), (inner_body_radius, lower_taper_height), (base_lower_side_radius - wall_thickness, base_side_height + wall_thickness), (base_foot_outer_radius - wall_thickness, wall_thickness), (base_foot_inner_radius - wall_thickness, wall_thickness), (base_dish_radius - wall_thickness, base_dish_height + wall_thickness), (base_mid_radius, base_recess_depth), (0.0, base_recess_depth + wall_thickness)]
shell = cq.Workplane('XZ').polyline(profile).close().revolve(360.0, (0.0, 0.0), (0.0, 1.0))
rim = cq.Workplane('XZ').moveTo(rim_center_radius, rim_center_height).circle(rim_tube_radius).revolve(360.0, (0.0, 0.0), (0.0, 1.0))
r = shell.union(rim).clean()
