# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# ruff: noqa
# mypy: ignore-errors
# NO CHECKED-IN PROTOBUF GENCODE
# source: objectron_annotation_subset.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "objectron_annotation_subset.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n!objectron_annotation_subset.proto\x12\x10\x64\x61\x33\x63\x61\x64.objectron"8\n\x11NormalizedPoint2D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05\x64\x65pth\x18\x03 \x01(\x02"V\n\x11\x41nnotatedKeyPoint\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x35\n\x08point_2d\x18\x03 \x01(\x0b\x32#.da3cad.objectron.NormalizedPoint2D"q\n\x10ObjectAnnotation\x12\x11\n\tobject_id\x18\x01 \x01(\x05\x12\x36\n\tkeypoints\x18\x02 \x03(\x0b\x32#.da3cad.objectron.AnnotatedKeyPoint\x12\x12\n\nvisibility\x18\x03 \x01(\x02"\\\n\x0f\x46rameAnnotation\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x05\x12\x37\n\x0b\x61nnotations\x18\x02 \x03(\x0b\x32".da3cad.objectron.ObjectAnnotation"H\n\x08Sequence\x12<\n\x11\x66rame_annotations\x18\x02 \x03(\x0b\x32!.da3cad.objectron.FrameAnnotationb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "objectron_annotation_subset_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_NORMALIZEDPOINT2D"]._serialized_start = 55
    _globals["_NORMALIZEDPOINT2D"]._serialized_end = 111
    _globals["_ANNOTATEDKEYPOINT"]._serialized_start = 113
    _globals["_ANNOTATEDKEYPOINT"]._serialized_end = 199
    _globals["_OBJECTANNOTATION"]._serialized_start = 201
    _globals["_OBJECTANNOTATION"]._serialized_end = 314
    _globals["_FRAMEANNOTATION"]._serialized_start = 316
    _globals["_FRAMEANNOTATION"]._serialized_end = 408
    _globals["_SEQUENCE"]._serialized_start = 410
    _globals["_SEQUENCE"]._serialized_end = 482
# @@protoc_insertion_point(module_scope)
